config/routes.rb
Rails.application.routes.draw do

  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :saying, presence: true, length: {maximum: 140, minimum: 10}, uniqueness: {case_sensitive: false}
  validates :author, presence: true, length: {maximum: 50, minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  # def create
  #  @quote = Quote.create(quote_params)
   # if @quote.invalid?
    #  flash [:error] = '<strong>Could not save</strong> the data you entered is invalid'
    # end
    # redirect_to root_path
  # end

  def about
  end
  
  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = "<strong>Could not save</strong> #{@quote.errors.full_messages.join(", ")}."
    end
    redirect_to root_path
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])

    if @quote.update_attributes(quote_params)
      redirect_to root_path
    else
      render :edit
    end
  end



  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SplurtyLk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<header>
<div class="col-xs-3">
  <%= link_to root_path, class: 'logo' do %>
  <div class="circle">
  <br />
  See if you
  <br />
  can get  
  <br />
  inspired!
  </div>
  <% end %>
</div>
<div class="col-sm-4 hidden-xs slogan">
  Splurting out inspirational quotes
</div>
<div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links"> 
<!-- Button trigger modal -->
  <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#newModal'} %>
  &nbsp; &nbsp;
  <!-- creates Link to the form to correct a wrong quote -->
  <% if @quote %>
    <%= link_to 'Correct', edit_quote_path(@quote) %>
  <% end %>
  &nbsp; &nbsp;
  <%= link_to 'About', about_path %>
    
</div>
</header>

<!-- Modal -->
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for Quote.new do |f| %>
        <%= f.input :saying, label: "What is the saying you want to add?", placeholder: "Fear is the desease. Hustle is the antidote." %>
        <br />
        <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Travis Kalanick" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Add Quote', class: 'btn btn-danger' %>
      </div>
        <% end %>
     </div>
   </div>
  </div>
</div>

<% if @quote %>
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Correct Your Quote</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @quote do |f| %>
        <%= f.input :saying, label: "What is the saying you want to add?", placeholder: "Fear is the desease. Hustle is the antidote." %>
        <br />
        <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Travis Kalanick" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Correct Quote', class: 'btn btn-danger' %>
      </div>
        <% end %>
     </div>
      
   </div>
  </div>
</div>
<% end %>

<hr />
<br class="clear" />

<div class="container">
  <% if flash[:error].present? %>
    <div class="cols-xs-10 col-xs-offset-1 alert alert-danger">
      <%= flash[:error].html_safe%>
    </div>
  <% end %>

  <%= yield %>

  
</div>

<div class="footer">
  <div class="container">
    <div class="col-xs-12 col-sm-6">
      <%= link_to "This isn't enough, I need more", root_path, class: 'next-quote' %>
    </div>
    <div class="col-xs-12 col-sm-6 footer-blurb">
      Humbly proceeded by L.Kus at lkcz04185@gmail.com </br>
      Want to build up your own web app - <a href="http://thefirehoseproject.com"> Learn how to code here </a>
    </div>
  </div>
</div>

</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
  <h1>About Quoteskeeper</h1>
  <p>
    Quoteskeeper was built by <a target="_blank" href="https://ch.linkedin.com/in/ladislav-kus-b032829a">Ladislav Kus
  </p>
  <br />
  <p>
  Solution Manager at IBM with 10+ years of experience in the IT Infrastructure Services.
  </p>
  <P>
  If you want to learn how to code - start <a target="_blank" href="http://www.thefirehoseproject.com/">here</a>.
  </p>

<div class="col-xs12 col-sm-4">
<%= image_tag 'LKus.JPG', class: 'img-responsive' %>
</div>
<div calss="col-xs-12 col-sm-7 col-sm-offset-1">
  <h2 class="text-center">Ladislav Kus</h2>
  <br />
  <p>
  As a Solution Manager I've been involved in a lot of engagement projects and contributed to signings of several long term outsourcing contracts in the value of 100+ Mio US$.
  </p>
</div>
  <br class="clear" />
 
</div>
</div>

app/views/quotes/edit.html.erb
      <%= simple_form_for @quote do |f| %>
        <%= f.input :saying, label: "Please correct the saying here:", placeholder: "Fear is the desease. Hustle is the antidote." %>
        <br />
        <%= f.input :author, label: "Correct the author of the quote here?", placeholder: "Travis Kalanick" %>
        <br />
        <button type="button" class="btn btn-default"><%= link_to 'Close', root_path %> </button>
        <%= f.submit 'Correct Quote', class: 'btn btn-danger' %>
      <% end %>

app/views/quotes/index.html.erb
<% if @quote.present? %>
<h2>
  <span>Quote No. <%= @quote.id %></span>
  &nbsp;
  <u>Inspirational quote:</u>
</h2>

<h1><%= @quote.saying %></h1>
<h2>- <%= @quote.author %></h2>

<% else %>
<h2>
  <span>No quotes exist so far, please contribute a quote.</span>
  </h2>
<% end %>

<br class="clear" />
<br />
<br />
<br />